name: dbt CI

on: [push, pull_request]

jobs:
  dbt:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dbt
      - name: Install dbt-snowflake
        run: pip install dbt-snowflake

      # 4. Create profiles.yml
      - name: Setup dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOL
          healthcare:
            target: ci
            outputs:
              ci:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
          EOL

      # 5. Install dbt deps
      - name: Install dbt deps
        run: dbt deps --project-dir dbt_pipeline --profiles-dir ~/.dbt

      # 6. Run dbt models
      - name: Run dbt
        run: dbt run --project-dir dbt_pipeline --profiles-dir ~/.dbt

      # 7. Run dbt tests
      - name: Test dbt
        run: dbt test --project-dir dbt_pipeline --profiles-dir ~/.dbt