project:
    name: month-3-snowflake-data-pipeline

postgres:
  port: 5434

mounts:
  - source: ./dags
    target: /usr/local/airflow/dags
  - source: ./src
    target: /usr/local/airflow/dags/src
  - source: ./dbt_pipeline
    target: /usr/local/airflow/dags/dbt_pipeline
  - source: ./schemas
    target: /usr/local/airflow/dags/schemas
  - source: ./sql
    target: /usr/local/airflow/dags/sql
  - source: ./data
    target: /usr/local/airflow/dags/data
# deploy:
#   airflow:
#     extraMounts:
      # - type: bind
      #   source: ./dags
      #   target: /usr/local/airflow/dags
      # - type: bind
      #   source: ./src
      #   target: /usr/local/airflow/dags/src
      # - type: bind
      #   source: ./dbt_pipeline
      #   target: /usr/local/airflow/dags/dbt_pipeline
      # - type: bind
      #   source: ./schemas
      #   target: /usr/local/airflow/dags/schemas
      # - type: bind
      #   source: ./sql
      #   target: /usr/local/airflow/dags/sql
      # - type: bind
      #   source: ./data
      #   target: /usr/local/airflow/dags/data